from pydantic import BaseModel, Field
from typing import List, Any, Optional, Literal

class Metadata(BaseModel):
    title: str = Field(description="e.g., 'Configurable Bloom Filter'")
    description: str
    primary_language: str = Field(default="python")

class Environment(BaseModel):
    dependencies: List[str] = Field(description="List of required external packages (e.g., ['mmh3', 'pytest']).")
    system_packages: Optional[List[str]] = Field(default=None, description="Required OS-level packages.")

class IOVariable(BaseModel):
    name: str
    type: str = Field(description="Type hint (e.g., 'int', 'List[str]')")
    description: str
    default_value: Optional[str] = Field(default=None, description="Omit if no default")

class ComponentSignature(BaseModel):
    inputs: List[IOVariable]
    returns: dict = Field(description="Dictionary containing 'type' and 'description' of the return value")

class ComponentBehavior(BaseModel):
    description: str = Field(description="Detailed logic requirements.")
    constraints: List[str] = Field(description="Algorithmic, memory, or library constraints.")
    edge_cases: List[str] = Field(description="Specific scenarios the TestAgent must cover.")

class ComponentExample(BaseModel):
    input: Any = Field(description="Valid representation of the input.")
    output: Any = Field(description="Valid representation of the expected output.")
    explanation: Optional[str] = Field(default=None)

class Component(BaseModel):
    name: str = Field(description="Name of the function or class.")
    type: Literal["function", "class"]
    signature: ComponentSignature
    behavior: ComponentBehavior
    examples: List[ComponentExample]

class StructuredSpec(BaseModel):
    metadata: Metadata
    environment: Environment
    components: List[Component]

class TestFailure(BaseModel):
    test_name: str = Field(description="Name of the test that failed")
    error_message: str = Field(description="Error message or exception description")
    stack_trace: str = Field(description="Full stack trace for the DebugAgent to analyze")

class TestResult(BaseModel):
    success: bool = Field(description="True if all tests passed, False otherwise")
    total_tests: int = Field(default=0)
    passed_tests: int = Field(default=0)
    failed_tests: int = Field(default=0)
    failures: List[TestFailure] = Field(default_factory=list, description="List of failed test details")
    execution_time_seconds: float = Field(default=0.0)

class GraphState(BaseModel):
    """
    Represents the state of our LangGraph system throughout the agentic execution loop.
    Adheres strictly to strict Pydantic parsing.
    """
    user_request: str = Field(description="The initial natural language request")
    
    # Agent Output Artifacts
    structured_spec: Optional[StructuredSpec] = Field(default=None, description="Output of the SpecAgent")
    generated_code: Optional[str] = Field(default=None, description="Python code generated by the CodeAgent")
    generated_tests: Optional[str] = Field(default=None, description="Pytest suite generated by the TestAgent")
    
    # Sandbox Execution Results
    test_result: Optional[TestResult] = Field(default=None, description="Output from the execution sandbox")
    
    # Loop Management
    revision_count: int = Field(default=0, description="Counter to prevent infinite loops during DebugAgent cycles")
    
    # Finalizations
    documentation: Optional[str] = Field(default=None, description="Obsidian-compatible markdown generated by DocsAgent")
    optimized_code: Optional[str] = Field(default=None, description="Mutated, efficient code generated by OptimizeAgent")